### ISSUE TITLE
Setting custom maxprocs value not possible

### ISSUE THREAD

**Issue by intjonathan** [newrelic/puppet-heka#10]
Setting maxprocs in global_config_settings like this:

``` puppet
    class {'::heka':
      global_config_settings => {
        maxprocs => 4,
      }
    }
```

results in maxprocs being declared twice, because the value is set statically [here](https://github.com/newrelic/puppet-heka/blob/HEAD/templates/heka.toml.erb#L12), and that variable is only going to be read from the params [here](https://github.com/newrelic/puppet-heka/blob/ff7a47c40593dc7e69d49fffb870223800476bd3/manifests/params.pp#L21). Seems like it should be a first-class argument in init.pp or just merge the `maxprocs` default into `$global_config_settings`.

**Comment by nickchappell** [comment]
I opened https://github.com/newrelic/puppet-heka/pull/11 to fix this.

I made this its own parameter so someone specifying a `global_config_settings` hash wouldn't accidentally clobber this value (and have Heka fall back to its own internal default of 1) if they forgot to include a `max_procs` parameter.

**Comment by nickchappell** [comment]
https://github.com/newrelic/puppet-heka/issues/11 was merged. I'll close this out.
