### ISSUE TITLE
Plugin should not permit empty type argument

### ISSUE THREAD

**Issue by intjonathan** [newrelic/puppet-heka#2]
Seems like this should not have a default undef, since an empty type value is meaningless.

https://github.com/newrelic/puppet-heka/blob/master/manifests/plugin.pp#L44

Looks like `validate_string()` call accepts `undef` as a valid empty string.

**Comment by nickchappell** [comment]
Good catch. I'll add a `validate_string()` function call into the defined type to check the `$type` parameter. I'll keep the default value as `undef` but catalog compilation will fail if a user keeps the default and doesn't specify something.

**Comment by intjonathan** [comment]
Why have a default undef when you could just require the argument?

-- 
Jonathan Owens
Site Engineering

On May 29, 2015 at 11:20:13, Nicholas Chappell (notifications@github.com) wrote:

Good catch. I'll add a validate_string function call into the defined type to check the $type parameter. I'll keep the default value as undef but catalog compilation will fail if a user keeps the default and doesn't specify something.

**Comment by nickchappell** [comment]
I created https://github.com/newrelic/puppet-heka/pull/9 to fix this.

**Comment by nickchappell** [comment]
https://github.com/newrelic/puppet-heka/issues/9 was merged. I'll close this out.
