### ISSUE TITLE
Package upgrades don't exactly work

### ISSUE THREAD

**Issue by intjonathan** [newrelic/puppet-heka#3]
Declaring `ensure => installed` in the Package resources doesn't upgrade the heka install if you specified a different version in the URL than what you have.

https://github.com/newrelic/puppet-heka/blob/master/manifests/install.pp#L30

**Comment by nickchappell** [comment]
I created https://github.com/newrelic/puppet-heka/pull/6 for this.

**Comment by nickchappell** [comment]
https://github.com/newrelic/puppet-heka/pull/6 was merged. I'll close this out.
